

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Window;
 
import javax.lang.model.util.ElementScanner14;
// import Window.User;
import javax.swing.*; // ana 3arf .* tb2a bate2a bs b3mlha
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
// import java.io.ClassNotFoundException;
import java.io.File;
import java.io.FileInputStream;
import java.util.*;

/**
 *
 * @author DELL
 */
public class LoginApplication extends javax.swing.JFrame {

    User curr = null;
    /**
     * Creates new form LoginApplication
     */
    public LoginApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">  

    private void initComponents() {
        // Function to initialize all components will used in this window

        jLabel1 = new JLabel();
        loginButton = new JButton(); 
        signUpButton = new JButton();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        nameField = new JTextField();
        passwordField = new JPasswordField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Login/SignUp");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt); // de alfunction al ht run 3shan t3ml al action
            }
        });

        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        jLabel3.setText("Password");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nameField, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(loginButton)
                .addGap(74, 74, 74)
                .addComponent(signUpButton)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(signUpButton))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>                        

    // doul ahm atneen 3ndna
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        /* 
         * tmm al login button hya htakhoud mn al user name wal password wtnady function al login
         * 
         */
        String name = nameField.getName();
        String pass = passwordField.getName();

        User currUser = login(name, pass);

        if(currUser == null)
        {
            try
            {
                JOptionPane.showMessageDialog(null,"This user does not exist!");
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else
        {
            UserOptions UserOptions = new UserOptions();
            setVisible(false);
            dispose();
            UserOptions.setVisible(true);
        }
    }     
    
    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
 
        String name = nameField.getText();
        char[] pass = passwordField.getPassword();
        String password = new String(pass);

        System.out.println(name + " " + password);

        boolean ok = signUp(name, password);

        if(ok)
        {
            try
            {
                JOptionPane.showMessageDialog(null,"This User Has Been Added Successfully");
                nameField.setText("");
                passwordField.setText("");
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else
        {
            try
            {
                JOptionPane.showMessageDialog(null,"This User Already Exists");
                nameField.setText("");
                passwordField.setText("");
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }      
        
    }                                     
                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private JButton loginButton; // ok button
    private JButton signUpButton; // cancel button
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPasswordField passwordField;
    private JTextField nameField;
    // End of variables declaration  
    
    // variables decleration out of gui
    private static ArrayList<User> allUsers = new ArrayList<>();

    // function to read all user from file and put it in array allUsers
    public static boolean readUserFile()
    {
        User user = null;
        try{
            File file = new File("Window\\UsersData.txt");
            FileOutputStream fos = new FileOutputStream(file,true);
            
        
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(null);
            oos.close();
            
            FileInputStream fis = new FileInputStream(file);
            ObjectInputStream ois = new ObjectInputStream(fis);
            
            if((user = (User)ois.readObject()) != null)
                allUsers.add(user);

            ois.close();
 
            return true;
            
        }catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null,e + " x");
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e + " Y");
        }
        catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,e + " Z");
        } 
        return false;
    }
    
    // function will used in this window
    public User login(String name, String passcode)
    {
        readUserFile();
        for(User user : allUsers)
        {
            if(user.getName().equals(name) && user.getPasscode().equals(passcode))
            return user;
        }
        return null;
    }    

    public static boolean signUp(String name, String passcode)
    {
        readUserFile();
        try
        {
            // if(allUsers.size()>0)
            // {
                for(User user : allUsers)
                if(user.getName() == name && user.getPasscode() == passcode)
                return false;
                
                writeUserInFile();
                allUsers.add(new User(name, passcode));
            // }
            // else
            // allUsers.add(new User(name, passcode));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e + " W");
        }
        
        
        

        return true;
    }

}
